class-attrs-all:
  pre-cluster-threshold: 0.72  # for License_Plate
  topk: 1
property:
  cluster-mode: 4
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/libnvds_infercustomparser.so
  gie-unique-id: 1
  infer-dims: 3;416;416
  labelfile-path: labels.txt
  maintain-aspect-ratio: 1
  model-color-format: 0
  net-scale-factor: 0.00392156862745098
  network-mode: 2
  network-type: 0
  num-detected-classes: 2
  offsets: 0;0;0
  output-blob-names: pred_logits;pred_boxes
  output-tensor-meta: 1
  parse-bbox-func-name: NvDsInferParseCustomDDETRTAO
  workspace-size: 1048576
  model-engine-file: /opt/nvidia/deepstream/deepstream-7.1/sources/apps/rt-detr_app/rt-detr_fp32_trtexec_docker.engine